/**
 * Community Templates for Trackmania Signpack Generator
 * Pre-built templates for common use cases
 */

export const COMMUNITY_TEMPLATES = {
    "Classic Racing": {
        description: "Traditional checkpoint style for racing",
        icon: "🏁",
        category: "racing",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 70,
            fontFamily: "Rajdhani",
            fontWeight: "700",
            textColor: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#2c3e50",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 4,
            borderColor: "#ffffff",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'gradientColor1', 'gradientColor2'],
        instructions: "Perfect for traditional racing maps. Change 'CP' to your preferred text!"
    },

    "Neon Cyber": {
        description: "Futuristic neon cyberpunk style",
        icon: "💡",
        category: "neon",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 70,
            fontFamily: "Orbitron",
            fontWeight: "900",
            textColor: "#00ffff",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#000000",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: false,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#00ffff",
            glowIntensity: 15,
            hologram: false,
            neon: true,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 8,
            borderWidth: 2,
            borderColor: "#00ffff",
            borderStyle: "solid",
            cornerRadius: 5,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'glowColor', 'borderColor'],
        instructions: "Cyberpunk vibes! Try different neon colors like #ff00ff or #00ff00"
    },

    "Clan Signpack": {
        description: "Perfect for clan/team identification",
        icon: "👥",
        category: "clan",
        difficulty: "beginner",
        settings: {
            textPrefix: "CLAN",
            fontSize: 70,
            fontFamily: "Bebas Neue",
            fontWeight: "400",
            textColor: "#FFD700",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#1a1a1a",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 6,
            shadowOffsetX: 3,
            shadowOffsetY: 3,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 3,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 4,
            borderColor: "#FFD700",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'borderColor', 'backgroundColor'],
        instructions: "Change 'CLAN' to your clan tag. Pick your team colors!"
    },

    "Minimalist Clean": {
        description: "Simple, professional checkpoints",
        icon: "✨",
        category: "professional",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 60,
            fontFamily: "Inter",
            fontWeight: "600",
            textColor: "#2c3e50",
            textTransform: "none",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#ffffff",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#bdc3c7",
            shadowBlur: 2,
            shadowOffsetX: 1,
            shadowOffsetY: 1,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 2,
            borderColor: "#95a5a6",
            borderStyle: "solid",
            cornerRadius: 8,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'backgroundColor', 'borderColor'],
        instructions: "Clean and simple. Works with any map theme!"
    },

    "Speed Run": {
        description: "High-visibility for technical tracks",
        icon: "⚡",
        category: "racing",
        difficulty: "beginner",
        settings: {
            textPrefix: "⚡",
            fontSize: 80,
            fontFamily: "Racing Sans One",
            fontWeight: "400",
            textColor: "#ff0000",
            textTransform: "uppercase",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#ffff00",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: false,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 4,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 6,
            borderColor: "#000000",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'backgroundColor'],
        instructions: "Maximum visibility! Great for precise checkpoint placement."
    },

    "Tournament Event": {
        description: "Professional style for competitions",
        icon: "🏆",
        category: "event",
        difficulty: "intermediate",
        settings: {
            textPrefix: "EVENT",
            fontSize: 65,
            fontFamily: "Orbitron",
            fontWeight: "700",
            textColor: "#00ffff",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#2c3e50",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 135,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 8,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#00ffff",
            glowIntensity: 10,
            hologram: false,
            neon: true,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 8,
            borderWidth: 3,
            borderColor: "#00ffff",
            borderStyle: "solid",
            cornerRadius: 5,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'gradientColor1', 'gradientColor2'],
        instructions: "Perfect for tournaments! Change EVENT to your tournament name."
    },

    "Retro Arcade": {
        description: "Nostalgic 8-bit gaming style",
        icon: "🕹️",
        category: "retro",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 55,
            fontFamily: "Press Start 2P",
            fontWeight: "400",
            textColor: "#00ff00",
            textTransform: "uppercase",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#000000",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "dots",
            patternColor: "#1a1a1a",
            patternSize: 8,
            noiseIntensity: 15,
            noiseScale: 0.5,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#00ff00",
            shadowBlur: 0,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#00ff00",
            glowIntensity: 8,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 4,
            borderColor: "#00ff00",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'glowColor', 'borderColor'],
        instructions: "8-bit nostalgia! Try colors like #00ff00, #ff00ff, or #ffff00"
    },

    "Rainbow Party": {
        description: "Fun, colorful checkpoint style",
        icon: "🌈",
        category: "fun",
        difficulty: "beginner",
        settings: {
            textPrefix: "✨",
            fontSize: 75,
            fontFamily: "Fredoka One",
            fontWeight: "400",
            textColor: "#ff00ff",
            textTransform: "uppercase",
            letterSpacing: 1,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#ffffff",
            gradientColor1: "#ff0080",
            gradientColor2: "#00ffff",
            gradientAngle: 90,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: true,
            strokeColor: "#ffffff",
            strokeWidth: 3,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: true,
            glitch: false,
            effectIntensity: 7,
            borderWidth: 5,
            borderColor: "#ffffff",
            borderStyle: "solid",
            cornerRadius: 10,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'gradientColor1', 'gradientColor2'],
        instructions: "Fun and colorful! Great for casual/party maps."
    },

    "Dark Mode Pro": {
        description: "Sleek dark theme for modern maps",
        icon: "🌙",
        category: "professional",
        difficulty: "intermediate",
        settings: {
            textPrefix: "CP",
            fontSize: 68,
            fontFamily: "Poppins",
            fontWeight: "600",
            textColor: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#0a0a0a",
            gradientColor1: "#1a1a1a",
            gradientColor2: "#0a0a0a",
            gradientAngle: 180,
            patternType: "carbon",
            patternColor: "#151515",
            patternSize: 12,
            noiseIntensity: 5,
            noiseScale: 2,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#4facfe",
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#4facfe",
            glowIntensity: 8,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 2,
            borderColor: "#333333",
            borderStyle: "solid",
            cornerRadius: 6,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'shadowColor', 'glowColor'],
        instructions: "Sleek and modern. Works great with dark-themed maps!"
    },

    "Gold Luxury": {
        description: "Premium gold style for special tracks",
        icon: "⭐",
        category: "luxury",
        difficulty: "intermediate",
        settings: {
            textPrefix: "★",
            fontSize: 72,
            fontFamily: "Montserrat",
            fontWeight: "800",
            textColor: "#FFD700",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#1a1a1a",
            gradientColor1: "#2c2416",
            gradientColor2: "#1a1a1a",
            gradientAngle: 135,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#996600",
            shadowBlur: 6,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: true,
            strokeColor: "#8B7500",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#FFD700",
            glowIntensity: 12,
            hologram: false,
            neon: false,
            metallic: true,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 7,
            borderWidth: 4,
            borderColor: "#FFD700",
            borderStyle: "solid",
            cornerRadius: 5,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'glowColor', 'borderColor'],
        instructions: "Luxurious gold theme. Perfect for special or championship tracks!"
    },

    "Spiral Psychedelic": {
        description: "Hypnotic spiral pattern background",
        icon: "🌀",
        category: "abstract",
        difficulty: "intermediate",
        settings: {
            textPrefix: "CP",
            fontSize: 70,
            fontFamily: "Audiowide",
            fontWeight: "400",
            textColor: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "pattern",
            backgroundColor: "#1a0033",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "spiral",
            patternColor: "#ff00ff",
            patternSize: 30,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#ff00ff",
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 3,
            textGlow: true,
            glowColor: "#ff00ff",
            glowIntensity: 15,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: false,
            pixel: false,
            retro: false,
            depth3d: false,
            effectIntensity: 5,
            borderWidth: 3,
            borderColor: "#ff00ff",
            borderStyle: "solid",
            cornerRadius: 8,
            signFormat: "6x1"
        },
        customizable: ['patternColor', 'textColor', 'backgroundColor'],
        instructions: "Trippy spiral pattern! Adjust pattern size for intensity."
    },

    "Geometric Diamonds": {
        description: "Modern geometric diamond pattern",
        icon: "💎",
        category: "abstract",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 68,
            fontFamily: "Montserrat",
            fontWeight: "700",
            textColor: "#00ffff",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "pattern",
            backgroundColor: "#0a0a1a",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "diamonds",
            patternColor: "#1a3a4a",
            patternSize: 40,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#00ffff",
            shadowBlur: 8,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#00ffff",
            glowIntensity: 12,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: false,
            pixel: false,
            retro: false,
            depth3d: false,
            effectIntensity: 5,
            borderWidth: 2,
            borderColor: "#00ffff",
            borderStyle: "solid",
            cornerRadius: 5,
            signFormat: "6x1"
        },
        customizable: ['patternColor', 'textColor', 'glowColor'],
        instructions: "Clean geometric diamond pattern. Adjust pattern size to taste!"
    },

    "Retro CRT Terminal": {
        description: "Old-school CRT monitor effect",
        icon: "📺",
        category: "retro",
        difficulty: "intermediate",
        settings: {
            textPrefix: ">",
            fontSize: 60,
            fontFamily: "JetBrains Mono",
            fontWeight: "500",
            textColor: "#00ff00",
            textTransform: "uppercase",
            letterSpacing: 1,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#0a0a0a",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: false,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: false,
            pixel: false,
            retro: true,
            depth3d: false,
            effectIntensity: 70,
            borderWidth: 4,
            borderColor: "#00ff00",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'effectIntensity'],
        instructions: "Classic CRT terminal look with scanlines and phosphor glow!"
    },

    "Pixelated Retro": {
        description: "Chunky pixelated effect",
        icon: "🎮",
        category: "retro",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 65,
            fontFamily: "Press Start 2P",
            fontWeight: "400",
            textColor: "#ff6b9d",
            textTransform: "uppercase",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#1a1a2e",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "checkerboard",
            patternColor: "#16213e",
            patternSize: 15,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 0,
            shadowOffsetX: 3,
            shadowOffsetY: 3,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: false,
            pixel: true,
            retro: false,
            depth3d: false,
            effectIntensity: 40,
            borderWidth: 5,
            borderColor: "#ff6b9d",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'backgroundColor', 'effectIntensity'],
        instructions: "Retro gaming vibes with pixelated text effect!"
    },

    "3D Pop-Out": {
        description: "Text with 3D depth layers",
        icon: "📦",
        category: "modern",
        difficulty: "intermediate",
        settings: {
            textPrefix: "CP",
            fontSize: 72,
            fontFamily: "Anton",
            fontWeight: "400",
            textColor: "#ff3366",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "conic",
            backgroundColor: "#1a1a1a",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 0,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: false,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: true,
            strokeColor: "#ffffff",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: false,
            pixel: false,
            retro: false,
            depth3d: true,
            effectIntensity: 60,
            borderWidth: 3,
            borderColor: "#ff3366",
            borderStyle: "solid",
            cornerRadius: 8,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'gradientColor1', 'gradientColor2', 'effectIntensity'],
        instructions: "Amazing 3D depth effect with conic gradient background!"
    },

    "Crosshatch Artist": {
        description: "Artistic crosshatch pattern",
        icon: "🎨",
        category: "artistic",
        difficulty: "intermediate",
        settings: {
            textPrefix: "ART",
            fontSize: 68,
            fontFamily: "Bebas Neue",
            fontWeight: "400",
            textColor: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: -5,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "pattern",
            backgroundColor: "#2d2d2d",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "crosshatch",
            patternColor: "#4a4a4a",
            patternSize: 25,
            noiseIntensity: 10,
            noiseScale: 1.5,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 5,
            shadowOffsetX: 3,
            shadowOffsetY: 3,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: false,
            pixel: false,
            retro: false,
            depth3d: false,
            effectIntensity: 5,
            borderWidth: 3,
            borderColor: "#ffffff",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'patternColor', 'patternSize'],
        instructions: "Artistic crosshatch pattern with sketch-like appearance."
    },

    "Scanline Arcade": {
        description: "Classic arcade machine scanlines",
        icon: "👾",
        category: "retro",
        difficulty: "beginner",
        settings: {
            textPrefix: "1UP",
            fontSize: 70,
            fontFamily: "Press Start 2P",
            fontWeight: "400",
            textColor: "#ffff00",
            textTransform: "uppercase",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#000033",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#ffff00",
            shadowBlur: 8,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#ffff00",
            glowIntensity: 10,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: true,
            pixel: false,
            retro: false,
            depth3d: false,
            effectIntensity: 60,
            borderWidth: 4,
            borderColor: "#ffff00",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'glowColor', 'effectIntensity'],
        instructions: "Authentic arcade scanlines! Try different colors for varied effects."
    },

    "Conic Sunset": {
        description: "Beautiful conic gradient sunset",
        icon: "🌅",
        category: "artistic",
        difficulty: "beginner",
        settings: {
            textPrefix: "☀",
            fontSize: 70,
            fontFamily: "Montserrat",
            fontWeight: "800",
            textColor: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "conic",
            backgroundColor: "#ff6b6b",
            gradientColor1: "#ff9068",
            gradientColor2: "#fd868c",
            gradientAngle: 90,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#ff4757",
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: true,
            strokeColor: "#ff4757",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#ffffff",
            glowIntensity: 8,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            scanlines: false,
            pixel: false,
            retro: false,
            depth3d: false,
            effectIntensity: 5,
            borderWidth: 3,
            borderColor: "#ffffff",
            borderStyle: "solid",
            cornerRadius: 15,
            signFormat: "6x1"
        },
        customizable: ['gradientColor1', 'gradientColor2', 'gradientAngle'],
        instructions: "Stunning conic gradient! Rotate the angle for different effects."
    }
};

/**
 * Get templates by category
 * @param {string} category - Category name
 * @returns {Object} Filtered templates
 */
export function getTemplatesByCategory(category) {
    const filtered = {};
    for (const [name, template] of Object.entries(COMMUNITY_TEMPLATES)) {
        if (template.category === category) {
            filtered[name] = template;
        }
    }
    return filtered;
}

/**
 * Get templates by difficulty
 * @param {string} difficulty - Difficulty level
 * @returns {Object} Filtered templates
 */
export function getTemplatesByDifficulty(difficulty) {
    const filtered = {};
    for (const [name, template] of Object.entries(COMMUNITY_TEMPLATES)) {
        if (template.difficulty === difficulty) {
            filtered[name] = template;
        }
    }
    return filtered;
}

/**
 * Get all categories
 * @returns {Array} Array of unique categories
 */
export function getAllCategories() {
    const categories = new Set();
    for (const template of Object.values(COMMUNITY_TEMPLATES)) {
        categories.add(template.category);
    }
    return Array.from(categories);
}

export default {
    COMMUNITY_TEMPLATES,
    getTemplatesByCategory,
    getTemplatesByDifficulty,
    getAllCategories
};
