/**
 * Community Templates for Trackmania Signpack Generator
 * Pre-built templates for common use cases
 */

export const COMMUNITY_TEMPLATES = {
    "Classic Racing": {
        description: "Traditional checkpoint style for racing",
        icon: "🏁",
        category: "racing",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 70,
            fontFamily: "Rajdhani",
            fontWeight: "700",
            textColor: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#2c3e50",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 4,
            borderColor: "#ffffff",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'gradientColor1', 'gradientColor2'],
        instructions: "Perfect for traditional racing maps. Change 'CP' to your preferred text!"
    },

    "Neon Cyber": {
        description: "Futuristic neon cyberpunk style",
        icon: "💡",
        category: "neon",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 70,
            fontFamily: "Orbitron",
            fontWeight: "900",
            textColor: "#00ffff",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#000000",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: false,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#00ffff",
            glowIntensity: 15,
            hologram: false,
            neon: true,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 8,
            borderWidth: 2,
            borderColor: "#00ffff",
            borderStyle: "solid",
            cornerRadius: 5,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'glowColor', 'borderColor'],
        instructions: "Cyberpunk vibes! Try different neon colors like #ff00ff or #00ff00"
    },

    "Clan Signpack": {
        description: "Perfect for clan/team identification",
        icon: "👥",
        category: "clan",
        difficulty: "beginner",
        settings: {
            textPrefix: "CLAN",
            fontSize: 70,
            fontFamily: "Bebas Neue",
            fontWeight: "400",
            textColor: "#FFD700",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#1a1a1a",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 6,
            shadowOffsetX: 3,
            shadowOffsetY: 3,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 3,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 4,
            borderColor: "#FFD700",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'borderColor', 'backgroundColor'],
        instructions: "Change 'CLAN' to your clan tag. Pick your team colors!"
    },

    "Minimalist Clean": {
        description: "Simple, professional checkpoints",
        icon: "✨",
        category: "professional",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 60,
            fontFamily: "Inter",
            fontWeight: "600",
            textColor: "#2c3e50",
            textTransform: "none",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#ffffff",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#bdc3c7",
            shadowBlur: 2,
            shadowOffsetX: 1,
            shadowOffsetY: 1,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 2,
            borderColor: "#95a5a6",
            borderStyle: "solid",
            cornerRadius: 8,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'backgroundColor', 'borderColor'],
        instructions: "Clean and simple. Works with any map theme!"
    },

    "Speed Run": {
        description: "High-visibility for technical tracks",
        icon: "⚡",
        category: "racing",
        difficulty: "beginner",
        settings: {
            textPrefix: "⚡",
            fontSize: 80,
            fontFamily: "Racing Sans One",
            fontWeight: "400",
            textColor: "#ff0000",
            textTransform: "uppercase",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#ffff00",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: false,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 4,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 6,
            borderColor: "#000000",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'backgroundColor'],
        instructions: "Maximum visibility! Great for precise checkpoint placement."
    },

    "Tournament Event": {
        description: "Professional style for competitions",
        icon: "🏆",
        category: "event",
        difficulty: "intermediate",
        settings: {
            textPrefix: "EVENT",
            fontSize: 65,
            fontFamily: "Orbitron",
            fontWeight: "700",
            textColor: "#00ffff",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#2c3e50",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 135,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 8,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: true,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#00ffff",
            glowIntensity: 10,
            hologram: false,
            neon: true,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 8,
            borderWidth: 3,
            borderColor: "#00ffff",
            borderStyle: "solid",
            cornerRadius: 5,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'gradientColor1', 'gradientColor2'],
        instructions: "Perfect for tournaments! Change EVENT to your tournament name."
    },

    "Retro Arcade": {
        description: "Nostalgic 8-bit gaming style",
        icon: "🕹️",
        category: "retro",
        difficulty: "beginner",
        settings: {
            textPrefix: "CP",
            fontSize: 55,
            fontFamily: "Press Start 2P",
            fontWeight: "400",
            textColor: "#00ff00",
            textTransform: "uppercase",
            letterSpacing: 0,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "solid",
            backgroundColor: "#000000",
            gradientColor1: "#667eea",
            gradientColor2: "#764ba2",
            gradientAngle: 45,
            patternType: "dots",
            patternColor: "#1a1a1a",
            patternSize: 8,
            noiseIntensity: 15,
            noiseScale: 0.5,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#00ff00",
            shadowBlur: 0,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#00ff00",
            glowIntensity: 8,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 4,
            borderColor: "#00ff00",
            borderStyle: "solid",
            cornerRadius: 0,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'glowColor', 'borderColor'],
        instructions: "8-bit nostalgia! Try colors like #00ff00, #ff00ff, or #ffff00"
    },

    "Rainbow Party": {
        description: "Fun, colorful checkpoint style",
        icon: "🌈",
        category: "fun",
        difficulty: "beginner",
        settings: {
            textPrefix: "✨",
            fontSize: 75,
            fontFamily: "Fredoka One",
            fontWeight: "400",
            textColor: "#ff00ff",
            textTransform: "uppercase",
            letterSpacing: 1,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#ffffff",
            gradientColor1: "#ff0080",
            gradientColor2: "#00ffff",
            gradientAngle: 90,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#000000",
            shadowBlur: 4,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: true,
            strokeColor: "#ffffff",
            strokeWidth: 3,
            textGlow: false,
            glowColor: "#00ff00",
            glowIntensity: 5,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: true,
            glitch: false,
            effectIntensity: 7,
            borderWidth: 5,
            borderColor: "#ffffff",
            borderStyle: "solid",
            cornerRadius: 10,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'gradientColor1', 'gradientColor2'],
        instructions: "Fun and colorful! Great for casual/party maps."
    },

    "Dark Mode Pro": {
        description: "Sleek dark theme for modern maps",
        icon: "🌙",
        category: "professional",
        difficulty: "intermediate",
        settings: {
            textPrefix: "CP",
            fontSize: 68,
            fontFamily: "Poppins",
            fontWeight: "600",
            textColor: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: 2,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#0a0a0a",
            gradientColor1: "#1a1a1a",
            gradientColor2: "#0a0a0a",
            gradientAngle: 180,
            patternType: "carbon",
            patternColor: "#151515",
            patternSize: 12,
            noiseIntensity: 5,
            noiseScale: 2,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#4facfe",
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            textStroke: false,
            strokeColor: "#000000",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#4facfe",
            glowIntensity: 8,
            hologram: false,
            neon: false,
            metallic: false,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 5,
            borderWidth: 2,
            borderColor: "#333333",
            borderStyle: "solid",
            cornerRadius: 6,
            signFormat: "6x1"
        },
        customizable: ['textColor', 'shadowColor', 'glowColor'],
        instructions: "Sleek and modern. Works great with dark-themed maps!"
    },

    "Gold Luxury": {
        description: "Premium gold style for special tracks",
        icon: "⭐",
        category: "luxury",
        difficulty: "intermediate",
        settings: {
            textPrefix: "★",
            fontSize: 72,
            fontFamily: "Montserrat",
            fontWeight: "800",
            textColor: "#FFD700",
            textTransform: "uppercase",
            letterSpacing: 3,
            textSkew: 0,
            textHorizontalAlign: "center",
            textVerticalAlign: "middle",
            backgroundType: "linear",
            backgroundColor: "#1a1a1a",
            gradientColor1: "#2c2416",
            gradientColor2: "#1a1a1a",
            gradientAngle: 135,
            patternType: "stripes",
            patternColor: "#34495e",
            patternSize: 20,
            noiseIntensity: 0,
            noiseScale: 1,
            imageOpacity: 50,
            imageBlendMode: "normal",
            textShadow: true,
            shadowColor: "#996600",
            shadowBlur: 6,
            shadowOffsetX: 2,
            shadowOffsetY: 2,
            textStroke: true,
            strokeColor: "#8B7500",
            strokeWidth: 2,
            textGlow: true,
            glowColor: "#FFD700",
            glowIntensity: 12,
            hologram: false,
            neon: false,
            metallic: true,
            chrome: false,
            rainbow: false,
            glitch: false,
            effectIntensity: 7,
            borderWidth: 4,
            borderColor: "#FFD700",
            borderStyle: "solid",
            cornerRadius: 5,
            signFormat: "6x1"
        },
        customizable: ['textPrefix', 'textColor', 'glowColor', 'borderColor'],
        instructions: "Luxurious gold theme. Perfect for special or championship tracks!"
    }
};

/**
 * Get templates by category
 * @param {string} category - Category name
 * @returns {Object} Filtered templates
 */
export function getTemplatesByCategory(category) {
    const filtered = {};
    for (const [name, template] of Object.entries(COMMUNITY_TEMPLATES)) {
        if (template.category === category) {
            filtered[name] = template;
        }
    }
    return filtered;
}

/**
 * Get templates by difficulty
 * @param {string} difficulty - Difficulty level
 * @returns {Object} Filtered templates
 */
export function getTemplatesByDifficulty(difficulty) {
    const filtered = {};
    for (const [name, template] of Object.entries(COMMUNITY_TEMPLATES)) {
        if (template.difficulty === difficulty) {
            filtered[name] = template;
        }
    }
    return filtered;
}

/**
 * Get all categories
 * @returns {Array} Array of unique categories
 */
export function getAllCategories() {
    const categories = new Set();
    for (const template of Object.values(COMMUNITY_TEMPLATES)) {
        categories.add(template.category);
    }
    return Array.from(categories);
}

export default {
    COMMUNITY_TEMPLATES,
    getTemplatesByCategory,
    getTemplatesByDifficulty,
    getAllCategories
};
